name: Request
description: File a request issue
title: "[Request] <join>"
labels: ["Join", "Request"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this form!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
  - type: checkboxes
    id: policies
    attributes:
      label: Policies
      description: By submitting this issue, you agree to follow [Policies](https://www.cancer.gov/policies). 
      options:
        - label: I agree to follow this project's Policies
          required: true
